package binaries

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Генерирует Kotlin object [ru.ozero.enginetor.dynamicmod.TorBinaryChecksums]
 * с эталонными SHA-256 для libtor-* и libiptproxy-* из binaries.lock.yaml.
 *
 * Используется engine-tor: после SplitInstall'а dynamic_tor нативки сверяются
 * с этими хешами; mismatch → deferredUninstall + Failed.
 */
abstract class GenerateTorChecksumsTask : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val lockFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun run() {
        val lockPath = lockFile.get().asFile.toPath()
        val lock =
            try {
                LockFileParser.parse(lockPath)
            } catch (e: LockFileException) {
                throw GradleException(e.message ?: "Lock file parse error", e)
            }

        val torArtifacts = lock.artifacts.filter {
            it.engine == TOR_ENGINE || it.engine == IPTPROXY_ENGINE
        }
        val byAbi: Map<String, List<Artifact>> =
            torArtifacts
                .filter { !it.abi.isNullOrBlank() }
                .groupBy { it.abi!! }
                .toSortedMap()

        val outRoot = outputDir.get().asFile
        val pkgDir = File(outRoot, PACKAGE_PATH)
        pkgDir.mkdirs()
        val target = File(pkgDir, "TorBinaryChecksums.kt")
        target.writeText(render(byAbi))
        logger.lifecycle(
            "[ozero-binaries] generated TorBinaryChecksums.kt with " +
                "${torArtifacts.size} entries across ${byAbi.size} ABI(s)",
        )
    }

    private fun render(byAbi: Map<String, List<Artifact>>): String = buildString {
        appendLine("// Generated by GenerateTorChecksumsTask. Do not edit by hand.")
        appendLine("package $PACKAGE_NAME")
        appendLine()
        appendLine("object TorBinaryChecksums {")
        appendLine("    val byAbi: Map<String, Map<String, String>> = mapOf(")
        for ((abi, items) in byAbi) {
            appendLine("        \"$abi\" to mapOf(")
            for (a in items.sortedBy { it.name }) {
                appendLine("            \"${a.name}\" to \"${a.sha256}\",")
            }
            appendLine("        ),")
        }
        appendLine("    )")
        appendLine("}")
    }

    private companion object {
        const val TOR_ENGINE = "tor"
        const val IPTPROXY_ENGINE = "iptproxy"
        const val PACKAGE_NAME = "ru.ozero.enginetor.dynamicmod"
        const val PACKAGE_PATH = "ru/ozero/enginetor/dynamicmod"
    }
}
