-keep class hev.** { *; }
-keep class ru.ozero.commonvpn.OzeroVpnService { *; }
-keep class ru.ozero.commonvpn.OzeroVpnService$* { *; }
-keep class ru.ozero.commonvpn.HevTunnelGateway { *; }
-keep class ru.ozero.commonvpn.NativeHevTunnelGateway { *; }
-keepclasseswithmembernames class * { native <methods>; }
