package ru.ozero.app.ui

enum class TopScreen {
    Main,
    Settings,
    Diagnostics,
    SplitTunnel,
    Servers,
    About,
    Logs,
    ByeDpiEngineSettings,
    UrnetworkEngineSettings,
    WarpEngineSettings,
    StrategyTest,
    StatsHistory,
    Backup,
    AutoModeSettings,
    Language,
    UrnetworkSharedTraffic,
    MasterDnsSettings,
    FptnSettings,
    SingboxSettings,
    SingboxAdvancedSettings,
    ChainSettings,
}
